### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by stainleebakhla** [dragg/MultiCloud#2]
Hi,

Could you please provide instructions on how to setup/install this on my local computer. I tried running this as a Laravel app, but I seem to get a lot of errors, such as views/layout file missing, and a lot of other css and js files are missing too. It would be really helpful if you could help me set this up.

Thanks.

**Comment by dragg** [comment]
Hi,

Sorry, I do not support this project. But along with Laravel I used AnguarJS 1.x so you will need install npm packages and try build front-end application with laravel elixir command (check docs of laravel 5.0 or 5.1). I hope it will help you. I did this project just for my diploma and to get base knowledge on Laravel with AngularJS.

Best Regards,

Nikolay
